### ISSUE TITLE
Watcher freezing on error

### ISSUE THREAD

**Issue by lexkrstn** [rogeriopvl/gulp-ejs#86] opened 2017-02-10 20:52 UTC
Hi. The problem I faced is that when an error occurs the error message is displayed in console and then the watcher/livereload stops further work. So if you then correct the error nothing will happen (although the watcher task in console is still running everything is stuck just showing the last error message).

Here is the code:
```javascript
const connect = require('gulp-connect')
...
gulp.task('ejs', () => {
	...
	return gulp.src('src/templates/*.ejs')
		.pipe(ejs({...}, {...}).on('error', gutil.log))
		.pipe(gulp.dest('./dist'))
		.pipe(connect.reload())
})

gulp.task('watch', function() {
	...
	gulp.watch('src/templates/**/*', ['ejs'])
});
```

**Comment by rogeriopvl** [comment] 2017-02-11 22:50
@coderlex thanks for the detailed feedback. I'm going to investigate this 👍

**Comment by rogeriopvl** [comment] 2017-02-12 09:32
@coderlex what version of `gulp-ejs` are you using?

**Comment by rogeriopvl** [comment] 2017-02-12 10:11
@coderlex I found the issue. You are returning from your task `return gulp.src...` this causes the task to stop. Just remove the return and it should work.

**Comment by coderlex** [comment] 2017-02-12 16:27
Thanks for your help.

I moved all the code from the `ejs` task to a function (named `ejsTask()`) and wrote 2 new tasks:
```javascript
gulp.task('ejs', () => ejsTask())
gulp.task('__ejs', () => { ejsTask() })
```
The last version is invoked only by watcher and is not allowed to be executed from the terminal | build task.

**Comment by krzkaczor** [comment] 2017-08-14 12:33
@rogeriopvl  thanks for providing the solution but do you think it's the right one? I am under the impression that there may be a bug in your plugin since all other plugins (SASS etc) work while returning stream from a task.

**Comment by mrDinckleman** [comment] 2018-02-01 11:29
Faced the same problem with Gulp v4. Since Gulp became asynchronous, I can't just remove `return`.
```js
var gulp = require('gulp'),
    ejs = require('gulp-ejs'),
    log = require('gulplog'),
    browserSync = require('browser-sync').create();

gulp.task('views', function() {
  return gulp.src('app/views/*.ejs')
    .pipe(ejs({}, {}, { ext: '.html' })).on('error', log.error)
    .pipe(gulp.dest('public'))
    .pipe(browserSync.stream());
});

gulp.task('watch', function() {
  browserSync.init({
    server: {
      baseDir: './public'
    }
  });

  gulp.watch('app/views/**/*.ejs', gulp.series('views'));
});

gulp.task('default', gulp.series('views', 'watch'));
```

**Comment by rogeriopvl** [comment] 2019-04-22 13:32
@mrDinckleman I've rewritten the plugin. Can you please try again with `gulp-ejs@4.0.0`?

I've tried to reproduce the issue with no success, so it should be fixed now.

**Comment by mrDinckleman** [comment] 2019-04-22 16:19
Thank you, now plugin is not freezing after an error occurs.

**Closed** 2019-04-22 16:26 UTC
